set(CMAKE_SYSTEM_NAME       Generic)
set(CMAKE_SYSTEM_PROCESSOR  ARM)


set(TOOLCHAIN_PREFIX arm-none-eabi-)

find_program(ARM_CC       ${TOOLCHAIN_PREFIX}gcc      REQUIRED)
find_program(ARM_CXX      ${TOOLCHAIN_PREFIX}g++      REQUIRED)
find_program(ARM_OBJCOPY  ${TOOLCHAIN_PREFIX}objcopy  REQUIRED)
find_program(ARM_OBJDUMP  ${TOOLCHAIN_PREFIX}objdump  REQUIRED)
find_program(ARM_SIZE     ${TOOLCHAIN_PREFIX}size     REQUIRED)

set(CMAKE_C_COMPILER        ${ARM_CC})
set(CMAKE_C_COMPILER_ID     GNU)
set(CMAKE_C_COMPILER_FORCED TRUE)

set(CMAKE_CXX_COMPILER      ${ARM_CXX})
set(CMAKE_CXX_COMPILER_ID   GNU)
set(CMAKE_CXX_COMPILER_FORCED TRUE)
